# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0008_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
